"""add profit column to transactions

Revision ID: ebe8ed8c9f70
Revises: b06142f98c5d
Create Date: 2025-11-15 07:34:37.074612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe8ed8c9f70'
down_revision: Union[str, Sequence[str], None] = 'b06142f98c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('profit', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('opening_trade_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'opening_trade_id')
    op.drop_column('transactions', 'profit')
    # ### end Alembic commands ###
